AppBundle\Entity\Comment:
    type: entity
    table: null
    repositoryClass: AppBundle\Repository\CommentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        author:
            type: string
            length: 255
        commentDate:
            type: datetime
        content:
            type: text
        vote:
            type: integer

    manyToOne:
        post:
            targetEntity: Post
            inversedBy: comments
            joinColumn:
                name: post_id
                referencedColumnName: id

    lifecycleCallbacks: {  }
